### ISSUE TITLE
Add Stimuli-Within-Block design?

### ISSUE THREAD

**Issue by becky-gilbert** [jake-westfall/pangea#3]
Can PANGEA handle a Stimuli-Within-Block design?

From the [JEP:G Crossed Power paper](http://jakewestfall.org/publications/crossed_power_JEPG.pdf), p. 2035:
> the full stimulus sample is divided into a smaller number of
comparable lists or blocks, and each participant is randomly assigned
to receive only one of these blocks. 

If not, I think this would be a useful feature.

**Comment by jake-westfall** [comment]
Yes, you can fit stimuli-within-block designs (or what we call "replicated" designs in our [Annual Review paper](http://jakewestfall.org/publications/JWK_AnnRev.pdf)) by adding a factor called "Blocks" to the design, and then having Participants and Stimuli both nested within Blocks. The Block factor will usually be **fixed**, but there might be special cases where it would make sense to treat the blocks as random.

**Comment by becky-gilbert** [comment]
Great, thanks!
